language: python
python:
  - '3.6'

# Handle git submodules yourself
git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive

before_script:
  - cd app/p8_pure_beurre/ && pip install pipenv && pipenv install

script: pipenv run python3 /app/p8_pure_beurre/manage.py test

env: DJANGO_SETTINGS_MODULE=app.p8_pure_beurre.app.settings.travis
